resources:
  repositories:
    - repository: ci-perl-helpers
      type: github
      name: houseabsolute/ci-perl-helpers
      ref: refs/heads/no-ci-more-customization
      endpoint: houseabsolute/ci-perl-helpers

stages:

  - template: templates/helpers/build.yml@ci-perl-helpers
    parameters:
      debug: true
      image_version: master

  - template: templates/helpers/linux.yml@ci-perl-helpers
    parameters:
      coverage: codecov
      coverage_partitions: 8
      debug: true
      use_default_perls: true
      image_version: master

  - template: templates/helpers/macos.yml@ci-perl-helpers
    parameters:
      debug: true
      use_default_perls: true

  - template: templates/helpers/windows.yml@ci-perl-helpers
    parameters:
      debug: true
      use_default_perls: true
